version: '2.3'

services:
  dev:
    container_name: enm-broady-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      CUDA_VISIBLE_DEVICES: 0,1
      PYTHONPATH: "/workspace:/workspace/backend"
      C_FORCE_ROOT: true
    runtime: nvidia
    restart: always
    tty: true
    stdin_open: true
    ipc: host
    ports:
      - "55554:22"  # for debug
      - "50001:8888"  # for debug
      - "55555:5555"  # for debug
    expose:
      - 8000
    volumes:
      - type: volume
        source: mldisk2
        target: /mldisk2
        volume:
          nocopy: true
      - type: volume
        source: nfs_shared_
        target: /mldisk/nfs_shared_
        volume:
          nocopy: true
      - type: volume
        source: nfs_shared
        target: /mldisk/nfs_shared
        volume:
          nocopy: true
      - type: volume
        source: mlsun
        target: /mlsun
        volume:
          nocopy: true
      - "${PWD}:/workspace"
      - "/media/mmlab/hdd:/hdd"


  triton-dev:
    build:
      context: ./triton/
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      CUDA_VISIBLE_DEVICES: 0,1
    expose:
      - 8000
      - 8001
      - 8002
    volumes:
      - "${PWD}/triton:/workspace"
      - "${PWD}/triton/model_repository:/models"


volumes:
  nfs_shared_:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume3/nfs_shared_"
  nfs_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"
  mlsun:
    driver_opts:
      type: "nfs"
      o: "addr=mlsun.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"
  mldisk2:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"
